# Generated by Django 3.0.5 on 2020-12-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsroom', '0003_auto_20201213_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poests',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='task',
            new_name='title',
        ),
    ]
